name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Install packages
        run: yarn && cd src/frontend-elements && yarn

      - name: Build
        run: yarn build
    
  deploy_testnet:
    name: Deploy the the built content on testnet hosting
    runs-on: ubuntu-latest
    needs: build
    environment: testnet
    steps:
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: lum-network
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  deploy_mainnet:
    name: Deploy the the built content on main net hosting
    runs-on: ubuntu-latest
    needs: build
    environment: mainnet
    steps:
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: lum-network
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels